export default {
  formatVersion: 2,
  id: 'sha256:039gEFdzfKtvphe1DPBgNiGvzNJbh8y9BusrnvqrfYY',
  localName: 'workstation_configuration_catalog',
  label: 'Workstation Configuration Catalog',
  version: 1,
  localParamsSchema: {
    additionalProperties: false,
    properties: {},
    type: 'object',
  },
  outputSchema: {
    additionalProperties: false,
    properties: {
      configurations: {
        items: {
          additionalProperties: false,
          properties: {
            aggregateVramGb: {
              type: 'number',
            },
            backend: {
              enum: ['cuda', 'metal'],
              type: 'string',
            },
            configuration: {
              type: 'string',
            },
            estimatedPriceUsd: {
              type: 'number',
            },
            estimatedSystemPowerW: {
              type: 'number',
            },
            gpu: {
              type: 'string',
            },
            gpuCount: {
              type: 'integer',
            },
            id: {
              type: 'string',
            },
            noiseClass: {
              enum: ['quiet', 'standard', 'loud'],
              type: 'string',
            },
            perfIndex: {
              type: 'number',
            },
            priceKind: {
              type: 'string',
            },
            sourceDate: {
              type: 'string',
            },
            sourceUrl: {
              type: 'string',
            },
            storageTb: {
              type: 'number',
            },
            systemRamGb: {
              type: 'number',
            },
            usableVramGb: {
              type: 'number',
            },
          },
          required: [
            'id',
            'configuration',
            'gpu',
            'gpuCount',
            'usableVramGb',
            'aggregateVramGb',
            'systemRamGb',
            'storageTb',
            'estimatedPriceUsd',
            'priceKind',
            'estimatedSystemPowerW',
            'perfIndex',
            'noiseClass',
            'backend',
            'sourceUrl',
            'sourceDate',
          ],
          type: 'object',
        },
        type: 'array',
      },
    },
    required: ['configurations'],
    type: 'object',
  },
  inputs: {},
  run: () => ({
    configurations: [
      {
        id: 'rtx-3090-value',
        configuration: 'RTX 3090 Value Tower',
        gpu: 'GeForce RTX 3090',
        gpuCount: 1,
        usableVramGb: 24,
        aggregateVramGb: 24,
        systemRamGb: 64,
        storageTb: 2,
        estimatedPriceUsd: 1900,
        priceKind: 'planning estimate; used GPU market varies',
        estimatedSystemPowerW: 620,
        perfIndex: 58,
        noiseClass: 'standard',
        backend: 'cuda',
        sourceUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3090-3090ti/',
        sourceDate: '2025-01-01',
      },
      {
        id: 'rtx-5090-creator',
        configuration: 'RTX 5090 Creator Tower',
        gpu: 'GeForce RTX 5090',
        gpuCount: 1,
        usableVramGb: 32,
        aggregateVramGb: 32,
        systemRamGb: 128,
        storageTb: 4,
        estimatedPriceUsd: 5200,
        priceKind: 'planning estimate; not a live quote',
        estimatedSystemPowerW: 900,
        perfIndex: 100,
        noiseClass: 'standard',
        backend: 'cuda',
        sourceUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5090/',
        sourceDate: '2025-01-30',
      },
      {
        id: 'dual-rtx-3090-lab',
        configuration: 'Dual RTX 3090 Lab Tower',
        gpu: 'GeForce RTX 3090',
        gpuCount: 2,
        usableVramGb: 24,
        aggregateVramGb: 48,
        systemRamGb: 128,
        storageTb: 4,
        estimatedPriceUsd: 3900,
        priceKind: 'planning estimate; used GPU market varies',
        estimatedSystemPowerW: 1050,
        perfIndex: 88,
        noiseClass: 'loud',
        backend: 'cuda',
        sourceUrl: 'https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3090-3090ti/',
        sourceDate: '2025-01-01',
      },
      {
        id: 'rtx-6000-ada-pro',
        configuration: 'RTX 6000 Ada Professional Tower',
        gpu: 'RTX 6000 Ada',
        gpuCount: 1,
        usableVramGb: 48,
        aggregateVramGb: 48,
        systemRamGb: 128,
        storageTb: 4,
        estimatedPriceUsd: 9000,
        priceKind: 'planning estimate; request a current vendor quote',
        estimatedSystemPowerW: 620,
        perfIndex: 74,
        noiseClass: 'quiet',
        backend: 'cuda',
        sourceUrl: 'https://www.nvidia.com/en-us/design-visualization/rtx-6000/',
        sourceDate: '2022-12-01',
      },
      {
        id: 'rtx-pro-6000-blackwell',
        configuration: 'RTX PRO 6000 Blackwell Tower',
        gpu: 'RTX PRO 6000 Blackwell',
        gpuCount: 1,
        usableVramGb: 96,
        aggregateVramGb: 96,
        systemRamGb: 256,
        storageTb: 4,
        estimatedPriceUsd: 12000,
        priceKind: 'planning estimate; request a current vendor quote',
        estimatedSystemPowerW: 950,
        perfIndex: 145,
        noiseClass: 'standard',
        backend: 'cuda',
        sourceUrl: 'https://www.nvidia.com/en-us/products/workstations/rtx-pro-6000/',
        sourceDate: '2025-03-18',
      },
      {
        id: 'mac-studio-m3-ultra',
        configuration: 'Mac Studio M3 Ultra 256 GB',
        gpu: 'Apple M3 Ultra integrated GPU',
        gpuCount: 1,
        usableVramGb: 192,
        aggregateVramGb: 192,
        systemRamGb: 256,
        storageTb: 2,
        estimatedPriceUsd: 7499,
        priceKind: 'planning estimate; configure a current Apple quote',
        estimatedSystemPowerW: 370,
        perfIndex: 82,
        noiseClass: 'quiet',
        backend: 'metal',
        sourceUrl: 'https://www.apple.com/mac-studio/specs/',
        sourceDate: '2025-03-05',
      },
    ],
  }),
}
