export default {
  formatVersion: 2,
  id: 'sha256:GygE4bN_4kbDjXcPjoF1FwGj39TgYTe0Vguwde5ZsrE',
  localName: 'workstation_requirements',
  label: 'Workload & Requirements',
  version: 1,
  localParamsSchema: {
    additionalProperties: false,
    properties: {
      budgetUsd: {
        default: 5500,
        description: 'Maximum planning budget for the complete workstation',
        minimum: 500,
        type: 'number',
      },
      concurrency: {
        default: 1,
        description: 'Simultaneous model requests',
        maximum: 16,
        minimum: 1,
        type: 'integer',
      },
      contextTokens: {
        default: 32768,
        description: 'Maximum tokens retained per simultaneous request',
        maximum: 262144,
        minimum: 2048,
        type: 'integer',
      },
      minimumSystemRamGb: {
        default: 64,
        description: 'Minimum acceptable system memory',
        minimum: 16,
        type: 'integer',
      },
      model: {
        default: 'qwen2.5-32b',
        enum: ['llama-3.1-8b', 'qwen2.5-32b', 'llama-3.3-70b'],
        type: 'string',
      },
      noisePreference: {
        default: 'any',
        enum: ['any', 'quiet'],
        type: 'string',
      },
      powerLimitW: {
        default: 1200,
        description: 'Maximum estimated wall power under sustained inference',
        minimum: 250,
        type: 'number',
      },
      quantization: {
        default: 'q4',
        enum: ['q4', 'q8', 'fp16'],
        type: 'string',
      },
      region: {
        default: 'US',
        enum: ['US'],
        type: 'string',
      },
      runtime: {
        default: 'any',
        enum: ['any', 'cuda', 'metal'],
        type: 'string',
      },
    },
    required: [],
    type: 'object',
  },
  outputSchema: {
    additionalProperties: false,
    properties: {
      budgetUsd: {
        default: 5500,
        description: 'Maximum planning budget for the complete workstation',
        minimum: 500,
        type: 'number',
      },
      concurrency: {
        default: 1,
        description: 'Simultaneous model requests',
        maximum: 16,
        minimum: 1,
        type: 'integer',
      },
      contextTokens: {
        default: 32768,
        description: 'Maximum tokens retained per simultaneous request',
        maximum: 262144,
        minimum: 2048,
        type: 'integer',
      },
      minimumSystemRamGb: {
        default: 64,
        description: 'Minimum acceptable system memory',
        minimum: 16,
        type: 'integer',
      },
      model: {
        default: 'qwen2.5-32b',
        enum: ['llama-3.1-8b', 'qwen2.5-32b', 'llama-3.3-70b'],
        type: 'string',
      },
      noisePreference: {
        default: 'any',
        enum: ['any', 'quiet'],
        type: 'string',
      },
      powerLimitW: {
        default: 1200,
        description: 'Maximum estimated wall power under sustained inference',
        minimum: 250,
        type: 'number',
      },
      quantization: {
        default: 'q4',
        enum: ['q4', 'q8', 'fp16'],
        type: 'string',
      },
      region: {
        default: 'US',
        enum: ['US'],
        type: 'string',
      },
      runtime: {
        default: 'any',
        enum: ['any', 'cuda', 'metal'],
        type: 'string',
      },
    },
    required: [
      'budgetUsd',
      'concurrency',
      'contextTokens',
      'minimumSystemRamGb',
      'model',
      'noisePreference',
      'powerLimitW',
      'quantization',
      'region',
      'runtime',
    ],
    type: 'object',
  },
  inputs: {},
  run: ({ params }) => ({ ...params }),
}
