nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
npmScopes:
  taskyon:
    npmRegistryServer: "https://registry.npmjs.org"
    npmPublishRegistry: "https://registry.npmjs.org"
