approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  taskyon:
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"
