services:
  taskyon:
    image: xyntopia/taskyon
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    ports:
      - '9000:9000'
    restart: always

  taskyon-debug:
    image: xyntopia/taskyon:debug
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debug
    ports:
      - '9000:9000'
    restart: no
    #volumes:
    #  - ~/.cache/yarn:/app/.yarn-cache

  taskyon-server:
    image: xyntopia/taskyon-server
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ssr-server
    ports:
      - '3000:3000'
    restart: always
    #volumes:
    #  - ~/.cache/yarn:/app/.yarn-cache
    env_file:
      - .env.local # we can declare GOOGLE_API_KEY this way..
