services:
  taskyon:
    image: xyntopia/taskyon
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:80'
    restart: always

  taskyon-debug:
    image: xyntopia/taskyon-space.dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prepare
    ports:
      - '8080:80'
    restart: always
    #volumes:
    #  - ~/.cache/yarn:/app/.yarn-cache
