services:
  taskyon:
    image: xyntopia/taskyon
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    ports:
      - '9000:9000'
    restart: always

  taskyon-debug:
    image: xyntopia/taskyon-space.dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debug
    ports:
      - '9000:9000'
    restart: no
    #volumes:
    #  - ~/.cache/yarn:/app/.yarn-cache
