# ---- base builder ----
FROM node:22-slim AS builder

WORKDIR /app

COPY package.json yarn.lock ./
COPY packages/relay ./packages/relay
COPY packages/taskyon ./packages/taskyon


# install *only relay's deps*, but resolved from root yarn.lock
RUN yarn install --production --ignore-workspace-root-check --cwd packages/relay

# ---- runtime ----
FROM node:22-slim

WORKDIR /app

# copy installed relay workspace from builder
COPY --from=builder /app/packages/relay ./packages/relay

WORKDIR /app/packages/relay

CMD ["yarn", "start"]
