import type { TaskNode, ToolBase } from './types'
import type OpenAI from 'openai'
import { useNlpWorker } from './webWorkerApi'
import { useTaskyonStore } from 'src/stores/taskyonState'
import { getTextFile } from './taskUtils'
import { useAppStateStore } from 'src/stores/appState'
import { useIpfs } from './ipfs'
import { getDatabase } from '../pglite.api'

const tystate = useTaskyonStore()
const state = useAppStateStore()

export const testPGLite = async () => {
  const db = await getDatabase('chatStore')
  return {
    db,
    pgvector: await db.exec('CREATE EXTENSION IF NOT EXISTS vector;'),
    createTable: await db.exec(`
      CREATE TABLE IF NOT EXISTS test (
        id SERIAL PRIMARY KEY,
        task TEXT,
        vec vector(3),
        done BOOLEAN DEFAULT false
      );
      INSERT INTO test (task, done) VALUES ('Install PGlite from NPM', true);
      INSERT INTO test (task, done) VALUES ('Load PGlite', true);
      INSERT INTO test (task, done) VALUES ('Create a table', true);
      INSERT INTO test (task, done) VALUES ('Insert some data', true);
      INSERT INTO test (task) VALUES ('Update a task');
      INSERT INTO test (task, vec) VALUES ('test1', '[1,2,3]');
      INSERT INTO test (task, vec) VALUES ('test2', '[4,5,6]');
      INSERT INTO test (task, vec) VALUES ('test3', '[7,8,9]');
    `),
    query: await db.sql`SELECT * from test WHERE id = 1;`,
    'vector query': await db.exec(`
      SELECT
        task,
        vec,
        vec <-> '[3,1,2]' AS distance
      FROM test;
    `),
  }
}

export const testIPFS = async () => {
  const markdownContent =
    '# Sample Markdown\n\nThis is a sample markdown file generated by Taskyon to test Gdrive functionality.\n\n' +
    new Date().toISOString()

  const { exportToIpfs } = await useIpfs()

  const cid = await exportToIpfs(markdownContent)

  return {
    cid,
  }

  //throw { message: 'could not found the task we just loaded!!' };
}

const mockTask: TaskNode = {
  role: 'assistant',
  id: 'test',
  content: { message: 'Sample content for task node' },
  debugging: { estimatedTokens: {} },
}

const mockChatMessages: OpenAI.Chat.Completions.ChatCompletionMessageParam[] = [
  { role: 'user', content: 'Hello, how are you?' },
  { role: 'assistant', content: "I'm good, thank you!" },
]

const mockTools: Record<string, ToolBase> = {
  tool1: {
    name: 'tool1',
    description: 'Tool 1 description',
    parameters: {
      type: 'object',
      properties: {
        param1: {
          type: 'string',
          description: 'some parameter1.',
        },
      },
      required: ['param1'],
    },
  },
  tool2: {
    name: 'tool2',
    description: 'Tool 2 description',
    parameters: {
      type: 'object',
      properties: {
        param2: {
          type: 'string',
          description: 'some parameter2.',
        },
      },
    },
  },
}

export async function testTransformersPipeline() {
  const { pipeline } = await import('@huggingface/transformers')
  const extractor = await pipeline('feature-extraction', 'Xenova/all-MiniLM-L6-v2')
  const output = await extractor('This is a simple test.', {
    pooling: 'mean',
    quantize: true,
    precision: 'binary',
  })
  /* Tensor {
  //   type: 'int8',
  //   data: Int8Array[49, 108, 24, ...],
  //   dims: [1, 48]
  }*/
  return output
}

export async function testVectorizerInitialization() {
  const nlpWorker = useNlpWorker()
  const modelName = state.llmSettings.vectorizationModel // Mock model name
  await nlpWorker.loadVecModel(modelName)
  await nlpWorker.loadVecTokenizer(modelName)
  return 'success'
}

export async function testVectorizeText() {
  const nlpWorker = useNlpWorker()
  const testText = 'Sample text for vectorization'
  const modelName = state.llmSettings.vectorizationModel // Mock model name
  const vector = await nlpWorker.vectorizeText(testText, modelName)
  const testSum = vector?.reduce((p, c) => p + c, 0)
  console.log('Vectorize Text Result Test Sum:', testSum)
  return testSum
}

export async function testEstimateChatTokens() {
  const nlpWorker = useNlpWorker()

  const tokens = await nlpWorker.estimateChatTokens(
    mockTask.content,
    mockChatMessages,
    mockTools,
    Object.values(mockTools).map((tool) => tool.name),
  )
  console.log('Estimate Chat Tokens Result:', tokens)
  return tokens
}

export async function markdownGeneration() {
  const tm = await tystate.getTaskManager()
  // first load the chat as mardown
  const yamlContent = await getTextFile('/tests/test_conversation.yaml')
  const lastLoadedTaskId = await tm.loadYamlConversation(yamlContent)
  //const newTaskId = await state.addMdTasks(markdownContent, undefined);
  // and delete this conversation again :)
  if (lastLoadedTaskId) {
    const markdown = await tm.chatToMarkdown(lastLoadedTaskId)
    await tm.deleteTaskThread(lastLoadedTaskId)
    return {
      markdown,
    }
  }
  throw new Error('could not found the task we just loaded!!')
}
