<template>
  <q-layout view="lHh LpR lfr">
    <q-page-container>
      <q-page class="q-pa-md q-gutter-md">
        <div class="text-h5">Taskyon Diagnostics</div>
        <q-btn flat label="Return to App" to="/"></q-btn>
        <q-btn
          outline
          label="Generate Diagnostics Report"
          @click="generateReport(detailed)"
        ></q-btn>
        <q-btn
          outline
          label="Only run first test"
          @click="generateReport(detailed, true)"
        ></q-btn>
        <q-btn
          v-if="diagnostics"
          outline
          label="download report"
          @click="downloadReport"
        ></q-btn>
        <q-toggle v-model="detailed" label="detailed"></q-toggle>
        <q-card flat bordered>
          <q-btn
            flat
            :icon="matContentCopy"
            @click="copyToClipboard(diagnostics)"
          ></q-btn>
          <pre>{{ diagnostics }}</pre>
        </q-card>
        <div v-for="(e, idx) of state.getErrors()" :key="idx">
          <p class="text-bold">{{ idx }}:</p>
          <pre>{{ e }}</pre>
        </div>
      </q-page>
    </q-page-container>
  </q-layout>
</template>

<script setup lang="ts">
import { useTaskyonStore } from 'stores/taskyonState';
import { generateCompleteChat } from 'src/modules/taskyon/promptCreation';
import { ref } from 'vue';
import { exportFile } from 'quasar';
import { dump } from 'js-yaml';
import { copyToClipboard } from 'src/modules/utils';
import { matContentCopy } from '@quasar/extras/material-icons';
import {
  testEstimateChatTokens,
  testVectorizeText,
} from 'src/modules/taskyon/tests';
import { getTextFile } from 'src/modules/taskyon/taskUtils';
import { useGdrive } from 'src/modules/gdrive';

const state = useTaskyonStore();
const diagnostics = ref<string>('');
const detailed = ref(true);

async function completionMessage() {
  const tm = await state.getTaskManager();
  const tyChat: Record<string, unknown> = {
    chatID: state.llmSettings.selectedTaskId,
  };
  if (state.llmSettings.selectedTaskId) {
    tyChat.taskIdChain = await tm.getTaskIdChain(
      state.llmSettings.selectedTaskId,
    );
    const task = await (
      await state.getTaskManager()
    ).getTask(state.llmSettings.selectedTaskId);
    if (task) {
      const res = await generateCompleteChat(task, state.llmSettings, tm);
      tyChat.thread = res;
    }
  }
  return tyChat;
}

async function runTest(
  name: string,
  testFunc: () => Promise<unknown> | unknown,
  details = false,
) {
  let result: Record<string, unknown> = {};
  console.log('run test:', name);
  try {
    let res = await testFunc();
    if (details) {
      result[name] = {
        status: 'OK',
        result: res,
      };
    } else {
      result[name] = 'OK';
    }
  } catch (error) {
    console.log(error);
    result[name] = {
      status: 'ERROR',
      message: 'an error occured during this test...',
      error,
    };
  }
  return dump(result, { skipInvalid: true });
}

async function generateReport(details = false, onlyFirst = false) {
  console.log('generating diagnostics report');

  diagnostics.value = `report_date: ${new Date().toISOString()}\n`;

  diagnostics.value += await runTest(
    'gdrive_upload',
    async () => {
      const { saveFileToGdrive } = useGdrive();

      const markdownContent =
        '# Sample Markdown\n\nThis is a sample markdown file generated by Taskyon to test Gdrive functionality.\n\n' +
        new Date().toISOString();
      const markdownFile = new File(
        [markdownContent], // Content as an array (required by File constructor)
        'taskyon_test.md', // Filename
        { type: 'text/markdown' }, // MIME type
      );

      saveFileToGdrive(
        markdownFile,
        state.appConfiguration.gdriveDir,
        markdownFile.name,
      );

      //throw { message: 'could not found the task we just loaded!!' };
    },
    details,
  );

  if (onlyFirst) {
    console.log('diagnostics:', diagnostics.value);
    return;
  }

  diagnostics.value += await runTest(
    'markdown_generation',
    async () => {
      const tm = await state.getTaskManager();
      // first load the chat as mardown
      const yamlContent = await getTextFile('/tests/test_conversation.yaml');
      const lastLoadedTaskId = await tm.loadYamlConversation(yamlContent);
      //const newTaskId = await state.addMdTasks(markdownContent, undefined);
      // and delete this conversation again :)
      if (lastLoadedTaskId) {
        const markdown = await tm.chatToMarkdown(lastLoadedTaskId);
        tm.deleteTaskThread(lastLoadedTaskId);
        return {
          markdown,
        };
      }
      throw { message: 'could not found the task we just loaded!!' };
    },
    details,
  );

  diagnostics.value += await runTest(
    'test_token_counter',
    testEstimateChatTokens,
    details,
  );
  diagnostics.value += await runTest(
    'test_vectorization',
    testVectorizeText,
    details,
  );

  diagnostics.value += await runTest('taskyon_data', getData, details);

  console.log('diagnostics:', diagnostics.value);
}

async function getData() {
  return dump(
    {
      browserInfo: {
        userAgent: navigator.userAgent,
        platform: navigator.platform,
        language: navigator.language,
        appName: navigator.appName,
        appVersion: navigator.appVersion,
        vendor: navigator.vendor,
        'crypto.subtle': crypto.subtle ? 'available' : 'not available',
      },
      windowInfo: {
        innerWidth: window.innerWidth,
        innerHeight: window.innerHeight,
        screenWidth: window.screen.width,
        screenHeight: window.screen.height,
        colorDepth: window.screen.colorDepth,
      },
      appInfo: {
        appConfiguration: state.appConfiguration,
      },
      errors: state.getErrors(),
      taskyonStoreDiagnostics: {
        SavedState: state.getStoredStateString(),
        CurrentState: state.getStateValues(),
      },
      CurrentChat: await completionMessage(),
    },
    { skipInvalid: true },
  );
}

async function downloadReport() {
  const fileName = 'taskyon_diagnostics_report.yaml';
  const fileContent = JSON.stringify(diagnostics.value);
  const mimeType = 'application/json';

  exportFile(fileName, fileContent, mimeType);
}

void completionMessage();

//const stateView = {...state}
</script>
