<template>
  <div class="q-gutter-md llm-providers">
    <div class="column q-gutter-sm items-center">
      <TyMarkdown
        class="q-pb-md"
        :src="
          $q.platform.within.iframe
            ? `## Welcome to Taskyon!

Please ensure that your application provides a valid API key. For more information, see our [integration guide](http://localhost:9000/docs/taskyon_integration#configuration). Alternatively, for development purposes, you can manually enter a key using the button below.`
            : `## Welcome to Taskyon!

To get started, you'll need an API key for an OpenAI-compatible AI service. You can choose from a variety of options, including third-party services or even hosting your own inference server.`
        "
      />
      <q-card-section v-if="state.usingFreeTaskyonKey">
        You’re currently using Taskyon’s free version, which includes access to basic models. For a
        better experience with higher-quality models, consider [signing
        up](https://taskyon.space/auth).
      </q-card-section>
      <div v-else class="row">
        <q-btn
          outline
          no-caps
          label="Use free Taskyon service (low quality)"
          to="/"
          @click="initFreeMode"
        ></q-btn>
        <InfoDialog>
          Pressing this button will add an API key which provides free API access to
          https://taskyon.space API for testing purposes & development.
        </InfoDialog>
      </div>
      <div v-if="tystate.availableProviders" class="text-italic">or</div>
      <div v-if="tystate.availableProviders" class="row items-center q-gutter-sm">
        <div>Choose a configured API:</div>
        <ApiSelect v-model="state.llmSettings.selectedApi" class="col-auto" />
      </div>
    </div>
    <q-expansion-item class="transparent">
      <template #header>
        <q-item-section class="text-bold"> Add API keys for AI services below: </q-item-section>
      </template>
      <q-card flat bordered>
        <q-card-section>
          You can specify connection settings (api keys etc...) for OpenAI compatible LLM Apis here.
          You can setup your own OpenAI-compatible server and connect to it or use other services:
        </q-card-section>

        <PasswordManager
          ref="passwords"
          copybtn
          :only-this-key="AiProvideKeyStoreName"
          @delete="
            (group, name) => {
              tystate.setProviderApiKey(name, undefined)
            }
          "
        />

        <q-card-section>
          <div>
            Activate new APIs by specifying new API keys below (taskyon API keys can be generated by
            a registered user here:
            <a href="https://taskyon.space/account" target="_blank" rel="noopener noreferrer"
              >Taskyon Account</a
            >
            ):
          </div>
          <div class="row justify-around q-gutter-sm q-pa-md">
            <template v-for="api in state.llmSettings.llmApis" :key="api.name">
              <DialogButton outline :label="api.name">
                <template #default="{ close }">
                  <q-card>
                    <q-card-section>
                      Add new Api Key for:
                      <span class="text-weight-bolder">{{ api.name }}</span>
                    </q-card-section>
                    <q-card-section @click.stop>
                      <SecretInput
                        v-model="currentNewPassword"
                        :label="api.name + ' key'"
                        filled
                        :data-cy="'add-' + api.name"
                        @keyup.enter="
                          () => {
                            addNewPw(api.name, currentNewPassword)
                            close()
                          }
                        "
                      />
                    </q-card-section>
                    <q-card-actions align="evenly">
                      <q-btn flat label="Cancel" />
                      <q-btn flat label="OK" @click="addNewPw(api.name, currentNewPassword)" />
                    </q-card-actions>
                  </q-card>
                </template>
              </DialogButton>
            </template>
          </div>
        </q-card-section>

        <q-expansion-item
          v-if="expertModeOn"
          class="q-pa-sm"
          dense
          label="Edit Apis"
          :icon="matEdit"
        >
          <TyMarkdown
            src="Here, we can add new, custom APIs to taskyon that we can connect to
it is possible to add your own LLM Inference Server to connect
to your own AI this way. E.g. using these methods:

- https://huggingface.co/blog/tgi-messages-api
- https://github.com/bentoml/OpenLLM

or with an llm proxy such as this one:  https://github.com/BerriAI/liteLLM-proxy
"
          />
          <JsonInput v-model="state.llmSettings.llmApis" filled />
        </q-expansion-item>
      </q-card>
      <div class="row q-py-md">
        <q-btn
          class="col"
          label="Go to Taskyon.space to retrieve an API key."
          outline
          no-caps
          icon="svguse:/taskyon_mono_opt.svg#taskyon"
          href="https://taskyon.space/account"
          target="_blank"
        />
        <InfoDialog
          info-text="
  https://taskyon.space is the official webpage of taskyon. You can
  retrieve API keys after logging in to your account.

  - Easily integrate taskyon into your webpage!
  - Access to more free models from a large selection of AI providers:

    Anthropic, OpenAI/ChatGPT, Google, Mistral, Meta, Huggingface and
    many more!
  "
        />
      </div>
      <q-expansion-item label="Retrieve Keys from other AI services">
        <q-item-label header>
          Manually configure & retrieve API keys (Setup a local, privacy-presevering server, a
          custom LLM AI server in your company etc...) Everything with an OpenAI compatible API will
          work:
        </q-item-label>
        <div class="row q-gutter-xs">
          <div class="col">
            <q-btn
              class="col"
              label="Use LLM inference using Huggingface Message API"
              outline
              no-caps
              href="https://huggingface.co/docs/text-generation-inference/en/messages_api"
              target="_blank"
            />
            <InfoDialog
              info-text="Huggingfaces message API https://huggingface.co/docs/text-generation-inference/en/messages_api is fully OpenAI compatible."
            />
          </div>
          <div class="col">
            <q-btn
              class="col"
              label="Go to OpenAI to retrieve an API key from OpenAI (not recommended)"
              outline
              no-caps
              href="https://platform.openai.com/account/api-keys"
              target="_blank"
            />
            <InfoDialog
              info-text="You can also get an API key from https://platform.openai.com/account/api-keys and manually
insert into the settings below."
            />
          </div>
          <div class="col">
            <q-btn
              label="Access keys via OpenRouter Dashboard (not recommended)"
              outline
              no-caps
              href="https://openrouter.ai/keys"
              target="_blank"
            />
            <InfoDialog
              info-text="Get an API key from https://www.openrouter.ai and use it for inference tasks"
            />
          </div>
        </div>
      </q-expansion-item>
    </q-expansion-item>
  </div>
</template>

<script setup lang="ts">
import { matEdit } from '@quasar/extras/material-icons'
import { freeKey } from 'src/assets/taskyon_free_key.json'
import { useAppStateStore } from 'src/stores/appState'
import { AiProvideKeyStoreName, useTaskyonStore } from 'src/stores/taskyonState'
import InfoDialog from '../InfoDialog.vue'
import JsonInput from '../JsonInput.vue'
import TyMarkdown from '../tyMarkdown.vue'
// TODO: separate user from supabase and only update the "user" from supabase...
//       this way we can make this component independent from supabase.
import { useQuasar } from 'quasar'
import { ref, useTemplateRef } from 'vue'
import DialogButton from '../DialogButton.vue'
import SecretInput from '../SecretInput.vue'
import ApiSelect from './ApiSelect.vue'
import PasswordManager from './PasswordManager.vue'
import type { KeyString } from '@taskyon/taskyon'

const state = useAppStateStore()
const tystate = useTaskyonStore()
const $q = useQuasar()
const passwords = useTemplateRef('passwords')

const expertModeOn = defineModel<boolean>('expertModeOn', { default: false })

async function initFreeMode() {
  state.llmSettings.selectedApi = 'taskyon'
  await tystate.setProviderApiKey('taskyon', freeKey as KeyString)
}

const currentNewPassword = ref<string>()
const addNewPw = async (name: string, newPw: string | undefined) => {
  await tystate.setProviderApiKey(name, newPw as KeyString)
  await passwords.value?.reloadSecrets()
  currentNewPassword.value = ''
}
</script>
