export type SecureFetchSmokeTarget = {
  name: string
  url: string
  kind: 'api' | 'binary' | 'http' | 'standards' | 'tls' | 'web'
  method?: 'GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
  headers?: Record<string, string>
  body?: string
  required?: boolean
  expectBody?: boolean
  expectTlsFailure?: boolean
  expectedTlsVersion?: 'TLS1_2' | 'TLS1_3'
}

export const SECURE_FETCH_SMOKE_TARGETS: readonly SecureFetchSmokeTarget[] = [
  {
    name: 'example-https',
    url: 'https://example.com/',
    kind: 'standards',
    required: true,
    expectedTlsVersion: 'TLS1_3',
  },
  { name: 'example-http', url: 'http://example.com/', kind: 'http', required: true },
  { name: 'example-org', url: 'https://example.org/', kind: 'web' },
  { name: 'example-net', url: 'https://example.net/', kind: 'web' },
  { name: 'never-ssl-http', url: 'http://neverssl.com/', kind: 'http' },
  { name: 'http-forever', url: 'http://httpforever.com/', kind: 'http' },
  {
    name: 'httpbin-json',
    url: 'https://httpbin.org/json',
    kind: 'api',
    required: true,
    expectedTlsVersion: 'TLS1_2',
  },
  { name: 'httpbin-http', url: 'http://httpbin.org/get', kind: 'http', required: true },
  {
    name: 'httpbin-chunked',
    url: 'https://httpbin.org/stream/3',
    kind: 'standards',
    required: true,
  },
  {
    name: 'httpbin-204',
    url: 'https://httpbin.org/status/204',
    kind: 'standards',
    expectBody: false,
  },
  { name: 'httpbin-redirect', url: 'https://httpbin.org/relative-redirect/2', kind: 'standards' },
  { name: 'httpbin-utf8', url: 'https://httpbin.org/encoding/utf8', kind: 'standards' },
  { name: 'httpbin-xml', url: 'https://httpbin.org/xml', kind: 'standards' },
  { name: 'httpbin-png', url: 'https://httpbin.org/image/png', kind: 'binary' },
  { name: 'httpbin-svg', url: 'https://httpbin.org/image/svg', kind: 'binary' },
  {
    name: 'httpbin-post-json',
    url: 'https://httpbin.org/post',
    kind: 'standards',
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: '{"taskyon":true}',
  },
  { name: 'postman-echo', url: 'https://postman-echo.com/get?source=taskyon', kind: 'api' },
  {
    name: 'postman-put',
    url: 'https://postman-echo.com/put',
    kind: 'standards',
    method: 'PUT',
    headers: { 'content-type': 'text/plain' },
    body: 'taskyon',
  },
  { name: 'jsonplaceholder', url: 'https://jsonplaceholder.typicode.com/todos/1', kind: 'api' },
  {
    name: 'jsonplaceholder-patch',
    url: 'https://jsonplaceholder.typicode.com/posts/1',
    kind: 'standards',
    method: 'PATCH',
    headers: { 'content-type': 'application/json' },
    body: '{"title":"taskyon"}',
  },
  { name: 'dummy-json', url: 'https://dummyjson.com/test', kind: 'api' },
  { name: 'restful-api', url: 'https://api.restful-api.dev/objects/7', kind: 'api' },
  { name: 'cat-fact', url: 'https://catfact.ninja/fact', kind: 'api' },
  { name: 'dog-api', url: 'https://dog.ceo/api/breeds/image/random', kind: 'api' },
  { name: 'random-user', url: 'https://randomuser.me/api/?results=1', kind: 'api' },
  { name: 'poke-api', url: 'https://pokeapi.co/api/v2/pokemon/ditto', kind: 'api' },
  { name: 'star-wars-api', url: 'https://swapi.dev/api/people/1/', kind: 'api' },
  {
    name: 'open-meteo',
    url: 'https://api.open-meteo.com/v1/forecast?latitude=0&longitude=0&current=temperature_2m',
    kind: 'api',
  },
  { name: 'github-api', url: 'https://api.github.com/repos/taskyon-space/taskyon', kind: 'api' },
  { name: 'gitlab-api', url: 'https://gitlab.com/api/v4/version', kind: 'api' },
  { name: 'codeberg-api', url: 'https://codeberg.org/api/v1/version', kind: 'api' },
  { name: 'npm-registry', url: 'https://registry.npmjs.org/typescript/latest', kind: 'api' },
  { name: 'pypi', url: 'https://pypi.org/pypi/requests/json', kind: 'api' },
  { name: 'crates-io', url: 'https://crates.io/api/v1/crates/serde', kind: 'api' },
  { name: 'rubygems', url: 'https://rubygems.org/api/v1/gems/rails.json', kind: 'api' },
  { name: 'packagist', url: 'https://repo.packagist.org/p2/monolog/monolog.json', kind: 'api' },
  { name: 'hacker-news', url: 'https://hacker-news.firebaseio.com/v0/item/8863.json', kind: 'api' },
  { name: 'open-library', url: 'https://openlibrary.org/works/OL45883W.json', kind: 'api' },
  { name: 'gutendex', url: 'https://gutendex.com/books/84', kind: 'api' },
  { name: 'crossref', url: 'https://api.crossref.org/works/10.5555/12345678', kind: 'api' },
  {
    name: 'arxiv-http',
    url: 'http://export.arxiv.org/api/query?search_query=all:electron&max_results=1',
    kind: 'http',
  },
  {
    name: 'wikipedia-api',
    url: 'https://en.wikipedia.org/api/rest_v1/page/summary/WebSocket',
    kind: 'api',
  },
  {
    name: 'wikidata-api',
    url: 'https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q42&format=json',
    kind: 'api',
  },
  {
    name: 'commons-api',
    url: 'https://commons.wikimedia.org/w/api.php?action=query&meta=siteinfo&format=json',
    kind: 'api',
  },
  {
    name: 'stack-exchange-api',
    url: 'https://api.stackexchange.com/2.3/info?site=stackoverflow',
    kind: 'api',
  },
  { name: 'rest-countries', url: 'https://restcountries.com/v3.1/alpha/de', kind: 'api' },
  {
    name: 'world-bank-api',
    url: 'https://api.worldbank.org/v2/country/DEU?format=json',
    kind: 'api',
  },
  {
    name: 'usgs-earthquakes',
    url: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson',
    kind: 'api',
  },
  { name: 'weather-gov', url: 'https://api.weather.gov/points/38.8894,-77.0352', kind: 'api' },
  {
    name: 'data-usa',
    url: 'https://api.datausa.io/api/data?Geography=04000US06&measure=Population&Year=latest',
    kind: 'api',
  },
  { name: 'frankfurter', url: 'https://api.frankfurter.app/latest?from=EUR&to=USD', kind: 'api' },
  {
    name: 'ecb-xml',
    url: 'https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml',
    kind: 'api',
  },
  {
    name: 'public-holidays',
    url: 'https://date.nager.at/api/v3/PublicHolidays/2026/DE',
    kind: 'api',
  },
  { name: 'ipify', url: 'https://api.ipify.org?format=json', kind: 'api' },
  { name: 'cloudflare-trace', url: 'https://www.cloudflare.com/cdn-cgi/trace', kind: 'standards' },
  { name: 'google-doh', url: 'https://dns.google/resolve?name=example.com&type=A', kind: 'api' },
  {
    name: 'cloudflare-doh',
    url: 'https://cloudflare-dns.com/dns-query?name=example.com&type=A',
    kind: 'api',
    headers: { accept: 'application/dns-json' },
  },
  { name: 'w3c-page', url: 'https://www.w3.org/', kind: 'web' },
  {
    name: 'w3c-pdf',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    kind: 'binary',
    required: true,
  },
  { name: 'rfc-editor', url: 'https://www.rfc-editor.org/rfc/rfc9110.txt', kind: 'standards' },
  { name: 'ietf', url: 'https://www.ietf.org/', kind: 'web' },
  { name: 'mdn', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API', kind: 'web' },
  { name: 'node-js', url: 'https://nodejs.org/', kind: 'web' },
  { name: 'deno', url: 'https://deno.com/', kind: 'web' },
  { name: 'bun', url: 'https://bun.sh/', kind: 'web' },
  { name: 'python-docs', url: 'https://docs.python.org/3/', kind: 'web' },
  { name: 'rust', url: 'https://www.rust-lang.org/', kind: 'web' },
  { name: 'go', url: 'https://go.dev/', kind: 'web' },
  { name: 'kernel', url: 'https://www.kernel.org/', kind: 'web' },
  { name: 'debian', url: 'https://www.debian.org/', kind: 'web' },
  { name: 'ubuntu', url: 'https://ubuntu.com/', kind: 'web' },
  { name: 'alpine', url: 'https://www.alpinelinux.org/', kind: 'web' },
  { name: 'arch-linux', url: 'https://archlinux.org/', kind: 'web' },
  { name: 'nixos', url: 'https://nixos.org/', kind: 'web' },
  { name: 'github', url: 'https://github.com/', kind: 'web' },
  { name: 'gitlab', url: 'https://gitlab.com/', kind: 'web' },
  { name: 'codeberg', url: 'https://codeberg.org/', kind: 'web' },
  { name: 'sourcehut', url: 'https://sr.ht/', kind: 'web' },
  { name: 'stack-overflow', url: 'https://stackoverflow.com/', kind: 'web' },
  { name: 'wikipedia', url: 'https://www.wikipedia.org/', kind: 'web' },
  { name: 'internet-archive', url: 'https://archive.org/', kind: 'web' },
  { name: 'project-gutenberg', url: 'https://www.gutenberg.org/', kind: 'web' },
  { name: 'nasa', url: 'https://www.nasa.gov/', kind: 'web' },
  { name: 'noaa', url: 'https://www.noaa.gov/', kind: 'web' },
  { name: 'usgs', url: 'https://www.usgs.gov/', kind: 'web' },
  { name: 'data-gov', url: 'https://data.gov/', kind: 'web' },
  { name: 'europa', url: 'https://european-union.europa.eu/', kind: 'web' },
  { name: 'gov-uk', url: 'https://www.gov.uk/', kind: 'web' },
  { name: 'canada', url: 'https://www.canada.ca/', kind: 'web' },
  { name: 'australia', url: 'https://www.australia.gov.au/', kind: 'web' },
  { name: 'united-nations', url: 'https://www.un.org/', kind: 'web' },
  { name: 'who', url: 'https://www.who.int/', kind: 'web' },
  { name: 'world-bank', url: 'https://www.worldbank.org/', kind: 'web' },
  { name: 'apache', url: 'https://www.apache.org/', kind: 'web' },
  { name: 'nginx', url: 'https://nginx.org/', kind: 'web' },
  { name: 'caddy', url: 'https://caddyserver.com/', kind: 'web' },
  { name: 'lets-encrypt', url: 'https://letsencrypt.org/', kind: 'web' },
  { name: 'fastly', url: 'https://www.fastly.com/', kind: 'web' },
  { name: 'mozilla', url: 'https://www.mozilla.org/', kind: 'web' },
  { name: 'chromium', url: 'https://www.chromium.org/', kind: 'web' },
  { name: 'webkit', url: 'https://webkit.org/', kind: 'web' },
  { name: 'curl', url: 'https://curl.se/', kind: 'web' },
  { name: 'openssl', url: 'https://www.openssl.org/', kind: 'web' },
  { name: 'sqlite', url: 'https://www.sqlite.org/', kind: 'web' },
  { name: 'postgresql', url: 'https://www.postgresql.org/', kind: 'web' },
  { name: 'redis', url: 'https://redis.io/', kind: 'web' },
  { name: 'tls-rsa-2048', url: 'https://rsa2048.badssl.com/', kind: 'tls' },
  { name: 'tls-ecdsa-p256', url: 'https://ecc256.badssl.com/', kind: 'tls' },
  { name: 'tls-ecdsa-p384', url: 'https://ecc384.badssl.com/', kind: 'tls' },
  { name: 'tls-sha256', url: 'https://sha256.badssl.com/', kind: 'tls' },
  { name: 'tls-san-base', url: 'https://badssl.com/', kind: 'tls' },
  {
    name: 'tls-many-sans-rejected',
    url: 'https://1000-sans.badssl.com/',
    kind: 'tls',
    expectTlsFailure: true,
  },
  { name: 'tls13-akamai', url: 'https://tls13.akamai.io/', kind: 'tls' },
  {
    name: 'tls-expired-rejected',
    url: 'https://expired.badssl.com/',
    kind: 'tls',
    expectTlsFailure: true,
  },
  {
    name: 'tls-wrong-host-rejected',
    url: 'https://wrong.host.badssl.com/',
    kind: 'tls',
    expectTlsFailure: true,
  },
  {
    name: 'tls-self-signed-rejected',
    url: 'https://self-signed.badssl.com/',
    kind: 'tls',
    expectTlsFailure: true,
  },
  {
    name: 'tls-untrusted-root-rejected',
    url: 'https://untrusted-root.badssl.com/',
    kind: 'tls',
    expectTlsFailure: true,
  },
] as const
