// vite.lib.config.ts
import { defineConfig } from 'vite'
import path from 'path'
import esbuild from 'esbuild'
//import dts from 'unplugin-dts/vite' // no advantage currently over the native vite-plugin-dts
//import dtsBundleGenerator from 'unplugin-dts-bundle-generator/vite'
//import dts from 'vite-plugin-dts'
//import dts from 'rollup-plugin-dts'

const libPath = path.resolve(__dirname, './src/index.ts')
console.log('building', libPath)

export default defineConfig({
  plugins: [
    /*dtsBundleGenerator({
      fileName: 'tyclient.d.ts',

      // ► 1.  Libraries – inline Zod, leave Vue as import
      libraries: {
        inlinedLibraries: ['@taskyon/taskyon', 'type-fest'],
        // If you also want to *keep* other libs external, list them here:
        importedLibraries: ['json-schema', 'zod'],
      },

      // ► 2.  Output tweaks
      output: {
        noBanner: true, // remove “Generated by …” comment
        sortNodes: true, // deterministic ordering
      },

      // ► 3.  Compilation (optional but faster)
      compilation: {
        preferredConfigPath: path.resolve(__dirname, './tsconfig.dts.json'),
        // skipTypeCheck: true, // uncomment if you already run `tsc --noEmit`
      },
    }),*/
    /*dts({
      insertTypesEntry: true,
      include: ['src/modules/'],
      outDir: 'public/lib',
      rollupTypes: true, // merge all declarations in a singe file
      declarationOnly: false, // only the d.ts. file.
      clearPureImport: true, // removes unused pure imports
    }),*/
    /* use the following to include "everything :)"
      insertTypesEntry: true,
      rollupTypes: true,
      copyDtsFiles: false, // Important for single file output
      include: ['src/modules/client', 'src/modules/taskyon'],
      outDir: 'public/lib',
      compilerOptions: {
        declarationMap: false,
      },
      afterBuild: () => {
        // Optional: Clean up residual files
      },
      */
  ],
  build: {
    minify: false,
    copyPublicDir: false,
    lib: {
      entry: libPath, // Adjust this to your actual library entry file
      name: 'tyclient',
      //formats: ['es'],
      //formats: ['cjs', 'es', 'umd'], // we only need this, if we don't have multiple output in rollupOptions
      fileName: (format) => `tyclient.${format}.js`,
    },
    // This ensures the output goes into public/
    outDir: 'dist',
    emptyOutDir: true, // Cleans old files before build
    rollupOptions: {
      external: ['vue', 'type-fest'], // externalize dependencies
      output: [
        {
          format: 'es',
          entryFileNames: 'tyclient.es.js', // Non-minified version
          preserveModules: false,
        },
        {
          format: 'umd',
          entryFileNames: 'tyclient.umd.js', // Non-minified version
          name: 'tyclient', // Global variable name for minified
        },
        {
          format: 'umd',
          entryFileNames: 'tyclient.umd.min.js', // Minified version
          name: 'tyclient', // Global variable name for minified
          plugins: [
            {
              name: 'minify',
              renderChunk(code) {
                return esbuild.transform(code, { minify: true }).then((result) => result.code)
              },
            },
          ],
        },
      ],
      /*plugins: [
        dts({ respectExternal: true }), // leaves externals like undici-types alone
      ],*/
    },
  },
})
